apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-agent-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/kogunlowo123/enterprise-agent-mesh
    targetRevision: HEAD
    path: deploy/helm/umbrella
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-agent-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
